### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by pfaffenrodt** [pfaffenrodt/android-any-adapter#93]
Check and validate with latest framworks.

Related PR not working https://github.com/pfaffenrodt/android-any-adapter/pull/92

**Comment by divyansh-dxn** [comment]
Hii @pfaffenrodt can you describe more what is this issue about?

**Comment by pfaffenrodt** [comment]
@divyansh-dxn I had no time to check if everything is fine. and maybe upgrade some things to unify with the latest version from leanback/recyclerview framework

**Comment by pfaffenrodt** [comment]
hacktoberfest is over
